---
title: "Scraping for spoana LT"
author: "y.hira"
date: "2/16/2019"
output: html_document
---

# Summary

プロ野球のデータをスクレイピングしcsvファイルとして書き出す  
スクレイピング対象のサイトはプロ野球データFreak(https://baseball-data.com/)  
公式サイトよりデータがリッチだったのでこのサイトにした  

# Library
```{r}
library(tidyverse)
library(rvest)
```

# Web Scraping

## service
```{r}
#-----Sevice-----

#空のデータフレーム作成
service <- data.frame(matrix(rep(NA, 6), nrow=1))[numeric(0), ]
name <- c("player", "percentage_service", "games_won_service", "games_total_service", "matches", "year")
names(service) <- name

for (i in 1991:2018) {
  
  URL <- paste0("https://www.atptour.com/en/stats/service-games-won/", i, "/all/all/")

  res <- URL %>% 
    read_html() %>% 
    html_node(xpath = '//*[@id="statsListingTableContent"]/table') %>% 
    html_table(fill = TRUE)

  name <- c("A", "B", "C", "D", "player", "percentage_service", "games_won_service", "games_total_service", "matches")
  names(res) <- name

  res <- res %>% 
    dplyr::select(-A, -B, -C, -D) %>% 
    na.omit() %>% 
    dplyr::mutate(year = i) %>% 
    dplyr::mutate_all(funs(as.character))
  
  #bind
  service <- dplyr::bind_rows(service, res)

  #1ページ取得したら1sec停止
  Sys.sleep(1)
  }
```

## return
```{r}
#-----return-----

#空のデータフレーム作成
return <- data.frame(matrix(rep(NA, 6), nrow=1))[numeric(0), ]
name <- c("player", "percentage_return", "games_won_return", "games_total_return", "matches", "year")
names(return) <- name

for (i in 1991:2018) {
  
  URL <- paste0("https://www.atptour.com/en/stats/return-games-won/", i, "/all/all/")

  res <- URL %>% 
    read_html() %>% 
    html_node(xpath = '//*[@id="statsListingTableContent"]/table') %>% 
    html_table(fill = TRUE)

  name <- c("A", "B", "C", "D", "player", "percentage_return", "games_won_return", "games_total_return", "matches")
  names(res) <- name

  res <- res %>% 
    dplyr::select(-A, -B, -C, -D) %>% 
    na.omit() %>% 
    dplyr::mutate(year = i) %>% 
    dplyr::mutate_all(funs(as.character))
  
  #bind
  return <- dplyr::bind_rows(return, res)

  #1ページ取得したら1sec停止
  Sys.sleep(1)
  }
```

## ranking

年末のランキングを集めたいが、微妙に日付が異なってfor文かけない...  
諦めて力づくでスクレイピングする
```{r}
#1991
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=1991-12-30&rankRange=0-100")

ranking <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 1991) %>% 
  dplyr::mutate_all(funs(as.character))

#1ページ取得したら1sec停止
Sys.sleep(1)

#1992
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=1992-12-28&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 1992) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#1993
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=1993-12-27&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 1993) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#1994
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=1994-12-26&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 1994) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#1995
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=1995-12-25&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 1995) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#1996
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=1996-12-30&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 1996) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#1997
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=1997-12-29&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 1997) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#1998
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=1998-12-28&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 1998) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#1999
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=1999-12-27&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 1999) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2000
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2000-12-25&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2000) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2001
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2001-12-31&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2001) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2002
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2002-12-30&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2002) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2003
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2003-12-29&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2003) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2004
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2004-12-27&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2004) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2005
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2005-12-26&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2005) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2006
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2006-12-25&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2006) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2007
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2007-12-31&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2007) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2008
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2008-12-29&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2008) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2009
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2009-12-28&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2009) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2010
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2010-12-27&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2010) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2011
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2011-12-26&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2011) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2012
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2012-12-31&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2012) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2013
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2013-12-30&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2013) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2014
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2014-12-29&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2014) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2015
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2015-12-28&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2015) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2016
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2016-12-26&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2016) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2017
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2017-12-25&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2017) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

#1ページ取得したら1sec停止
Sys.sleep(1)

#2018
URL <- paste0("https://www.atptour.com/en/rankings/singles?rankDate=2018-12-31&rankRange=0-100")

res <- URL %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="rankingDetailAjaxContainer"]/table') %>% 
  html_table(fill = TRUE) %>% 
  dplyr::mutate(year = 2018) %>% 
  dplyr::mutate_all(funs(as.character))

#bind
ranking <- dplyr::bind_rows(ranking, res)

ranking <- ranking %>% 
  dplyr::select(-Move, -Country, -`Points Dropping`, -`Next Best`)

name <- c("ranking", "player", "age", "points", "tourn_played", "year")
names(ranking) <- name
```

# Write csv file
```{r}
service %>% readr::write_csv("service.csv")
return %>% readr::write_csv("return.csv")
ranking %>% readr::write_csv("ranking.csv")
```